### ISSUE TITLE
Отсутствует resource "yandex_alb_target_group"

### ISSUE THREAD

**Issue by patsevanton** [terraform-yacloud-modules/terraform-yandex-alb#54]
Коллеги, в нашем коде отсутствует resource "yandex_alb_target_group"

В интернете при использовании ALB используется resource "yandex_alb_target_group"
https://github.com/yandex-cloud-examples/yc-dmz-with-high-available-ngfw/blob/main/load-balancer.tf#L70
https://github.com/ImshaBy/imshaby-api/blob/master/iac/tf/api/lb.tf#L6
https://github.com/MakarovS96/terraform_sf/blob/main/main.tf#L65
https://github.com/SultankaReal/terraform-create-alb-load-balancer/blob/main/alb_http.tf#L1

Стоит ли добавить resource "yandex_alb_target_group" в наш код?

**Comment by kvendingoldo** [comment]
Я использовал этот модуль только вместе с  `terraform-yacloud-modules/instance-group/yandex` модулем, откуда можно было получать target_group_id через `target_group_id` аутпут. В целом, я согласен что стоит опциально добавить создание yandex_alb_target_group в этот модуль
